openapi: 3.0.0
info:
  title: Projects
  version: '0.1'
  contact:
    name: 4uth API Team
    email: apis@4uth.net
  description: Create and manage Projects within your 4uth console
servers:
  - url: 'http://eu.api.4uth.net/console/v1'
    description: For accounts with data residency in the EU
  - url: 'http://us.api.4uth.net/console/v1'
    description: For accounts with data residency in the US
  - url: 'http://localhost:3000/console/v1'
    description: For local development
tags:
  - name: project
    description: Relating to a project.
paths:
  '/projects/{project_id}':
    parameters:
      - name: project_id
        description: The ID of the Project
        schema:
          $ref: '../../common/models/DataTypes.v1.yaml#/components/schemas/UUID'
        in: path
        required: true
    get:
      summary: Retrieve Project
      operationId: get-project
      tags:
        - project
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/Project.v1.yaml
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin-All'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ../../common/models/ProblemDetailsBase.v1.yaml
      description: Get a Project identified by `project_id`.
      parameters: []
    delete:
      summary: ''
      description: Delete the Project from the projects collection identified by `project_id`
      operationId: delete-projects
      responses:
        '204':
          description: No Content
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin-All'      
      parameters: []
      tags:
        - project
  '/projects':
    post:
      summary: Create a Project
      description: Create a Project
      operationId: create-project
      tags:
        - project
      responses:
        '201':
          description: Created
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin-All'
          content:
            application/hal+json:
              schema:
                $ref: ./models/Project.v1.yaml
              examples:
                basic:
                  value:
                    project_id: 523
                    name: My test project
                    created_at: '2020-06-01T16:43:30+00:00'
                    updated_at: '2020-06-01T16:43:30+00:00'
                    _links:
                      self: /projects/523
                    credentials: []
                    capabilities: []
      requestBody:
        description: A JSON payload for the Project that is to be created.
        content:
          application/json:
            schema:
              $ref: ./models/ProjectCreatePayload.v1.yaml
            examples:
              basic:
                value:
                  name: My test project
                  authentication: []
                  capabilities: []
    get:
      summary: Retrieve a collection of projects
      operationId: get-projects
      description: Get a full list of Projects or filter by query parameter.
      tags:
        - project
      parameters:
        - name: name
          schema:
            type: string
            example: hello
          in: query
          description: The name of the project
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageNumber'
        #- $ref: '#/components/parameters/sortBy' `name` is the only input parameter so has to be sorted by name for now
        - $ref: '#/components/parameters/sortOrder'
      responses:
        '200':
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin-All'
          content:
            application/hal+json:
              schema:
                $ref: ./models/ProjectCollection.v1.yaml
              examples:
                basic:
                  value:
                    page_size: 10
                    page_number: 1
                    total_pages: 1
                    total_items: 2
                    _embedded:
                      projects:
                        - _links:
                            self:
                              href: /projects/c69bc0e6-a429-11ea-bb37-0242ac130002
                          project_id: c69bc0e6-a429-11ea-bb37-0242ac130002
                          name: My first project
                          created_at: '2020-06-01T16:43:30+00:00'
                          updated_at: '2020-06-01T16:43:30+00:00'
                          credentials: []
                          capabilities: []
                        - _links:
                            self:
                              href: /projects/c69bc0e6-a429-11ea-bb37-0242ac130003
                          project_id: c69bc0e6-a429-11ea-bb37-0242ac130003
                          name: My second project
                          created_at: '2020-06-01T16:43:30+00:00'
                          updated_at: '2020-06-01T16:43:30+00:00'
                          credentials: []
                          capabilities: []
                    _links:
                      first:
                        href: '/projects/page=1&page_size=10'
                      last:
                        href: '/projects/page=1&page_size=10'
                      next:
                        href: null
                      prev:
                        href: null
                      self:
                        href: /projects?page_size=10

components:

  # Reusable parameters
  parameters:
    # Collections
    sortBy:
      name: sortby
      description: Identifies the field that the results will be sorted by
      in: query
      schema:
        type: string
    sortOrder:
      name: sortorder
      description: Identifies how the results will be sorted based on the `sortby` field.
      in: query
      schema:
        type: string
        enum:
          - 'asc'
          - 'dsc'
        default: 'asc'
    pageNumber:
      name: page_number
      description: The page number being requested
      in: query
      schema:
        type: integer
        example: 10
        default: 1
        minimum: 1
    pageSize:
      name: page_size
      description: The number of items to be returned for the page being requested
      in: query
      schema:
        type: integer
        example: 10
        default: 10
        minimum: 1
        maximum: 100
          
  # Reusable Headers        
  headers:
    X-RateLimit-Limit:
      description: Request limit per hour
      schema:
        type: integer
      example: 100
      required: true
    X-RateLimit-Remaining:
      description: Remaining requests for the hour
      schema:
        type: integer
      example: 94
      required: true
    Access-Control-Allow-Origin-All:
      description: Allow CORS
      schema:
        type: string
        enum:
          - "*"
      required: true
    
        
