openapi: 3.0.0
info:
  title: tru.ID Basics APIs
  version: ""
  contact:
    name: tru.ID API Team
    email: feedback@tru.id
  description: |
    # Introduction

    The tru.ID API uses [OAuth2](#tag/oauth2) Access Tokens for authentication. Access Tokens are created using the [/token endpoint](#operation/oauth2-token) with a valid `client_id` and `client_secret`. `client_id` and `client_secret` credentials are obtained by [creating a Project](#operation/create-project).

    The [**tru.ID Workspaces API**](#tag/workspaces_v0.2) provides access to manage Workspaces, which are containers for users accounts and billing accounts.

    The [**tru.ID Projects API**](#tag/projects_v0.2) allows the management of the projects under your Workspace, to manage the projects credentials and logically group API calls.

    The [**tru.ID Members API**](#tag/members_v0.2) provides functionality to manage all of the members under the Workspace.

servers:
  - url: "https://{data_residency}.api.tru.id"
    description: For accounts with data residency in the EU, IN, or US
    variables:
      data_residency:
        default: eu
        enum:
          - eu
          - in
          - us
tags:
  - name: oauth2_v1
    x-displayName: v1
    description: Relating to the OAuth2 Provider
  - name: projects_v0.2
    x-displayName: v0.2
    description: A project is container for configuration on the platform. A project contains credentials used to authenticate API requests with a project `mode` and per-product configuration.
  - name: workspaces_v0.2
    x-displayName: v0.2
    description: Relating to a workspace.
  - name: hide
    description: Tags that should not be rendered
  - name: members_v0.2
    x-displayName: v0.2
    description: Relating to Members.

x-tagGroups:
  - name: oAuth2
    tags:
      - oauth2_v1
  - name: Workspaces
    tags:
      - workspaces_v0.2
  - name: Projects
    tags:
      - projects_v0.2
  - name: Members
    tags:
      - members_v0.2

paths:
  /oauth2/v1/auth:
    get:
      summary: Obtain an authorization grant (Restricted Usage)
      description: "Used within the OAuth2 flow. Used to request access to a resource from the resource owner. Only supported for tru.ID owned applications. See https://tools.ietf.org/html/rfc6749#section-3.1"
      operationId: oauth2-auth
      tags:
        - hide
      parameters:
        - name: response_type
          description: "Used as part of an Authorization Code Grant. Expected to have a value of `code`. See https://tools.ietf.org/html/rfc6749#section-4.1"
          in: query
          schema:
            type: string
            example: code
        - name: client_id
          description: The client identifier. Only issued for use with `/auth` to internal tru.ID applications.
          in: query
          schema:
            type: string
            example: 63f16604-2b4f-4e45-b32f-59290507fe93
        - name: state
          description: |
            An opaque value used by the client to maintain state between the request and callback. The authorization server includes this value when redirecting the user-agent back to the client.
            See: https://tools.ietf.org/html/rfc6749#section-4.1.1"
          in: query
          schema:
            type: string
        - $ref: "#/components/parameters/scope"
        - name: redirect_url
          description: "After completing the interaction with the resource owner, the authorization server directs the resource owner's user-agent back the location identified by `redirect_url`."
          in: query
          schema:
            type: string
            format: uri
      responses:
        "302":
          description: Redirects to the `redirect_url`.
          headers:
            Location:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Location
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
  /oauth2/v1/token:
    post:
      summary: Create an Access Token
      description: |
        Creates an Access Token. Access Tokens are credentials used to authenticate API interactions.
        With the tru.ID platform, the usage is to create an Access Token from a `client_id` and `client_secret`.

        To obtain a `client_id` and `client_secret` you must first [create a Project](#operation/create-project).
      operationId: oauth2-token
      security:
        - BasicAuth: []
      tags:
        - oauth2_v1
      requestBody:
        description: |
          The request body should match the [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4) flow.
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              description: |
                Create an Access Token authenticated using a `client_id` and `client_secret` as part of a [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
                The resulting token is used to access any API endpoints.
              properties:
                grant_type:
                  description: |
                    The type of grant; in this case a [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
                    Value must be set to `client_credentials`.
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                scope:
                  $ref: "#/components/schemas/OAuth2Scope"
      responses:
        "200":
          description: The Access Token was successfully created.
          content:
            application/json:
              schema:
                type: object
                description: |
                  The response to a [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
                properties:
                  access_token:
                    description: The Access Token to be used when authenticating with API endpoints
                    type: string
                    example: 2YotnFZFEjr1zCsicMWpAA
                  token_type:
                    description: |
                      The type of token in `access_token`. The token type returned will always be `bearer`.
                      For more information see [The OAuth 2.0 Authorization Framework: Bearer Token Usage](https://tools.ietf.org/html/rfc6750)
                    type: string
                    enum:
                      - bearer
                    example: bearer
                  expires_in:
                    description: The time in seconds when the token will expire.
                    type: integer
                    example: 3600
                  scope:
                    $ref: "#/components/schemas/OAuth2Scope"
              examples:
                phone_check:
                  value:
                    access_token: 2YotnFZFEjr1zCsicMWpAA
                    token_type: bearer
                    expires_in: 3600
                    scope: phone_check coverage
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
  /oauth2/v1/revoke:
    post:
      summary: Revoke an token
      description: Revoke a token from the OAuth2 provider.
      operationId: oauth2-revoke
      security:
        - BasicAuth: []
      tags:
        - oauth2_v1
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              description: |
                The response to a [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
              properties:
                token:
                  description: The token to be revoked
                  type: string
                  example: 2YotnFZFEjr1zCsicMWpAA
                token_type_hint:
                  description: A hint to help the OAuth2 provider identify the type of token
                  type: string
                  enum:
                    - access_token
                    - refresh_token
                  example: access_token
      responses:
        "200":
          description: Response whether the Access Token was valid or invalid.
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
  /oauth2/v1/sessions/logout:
    get:
      summary: Logout of the current user session (Restricted Usage)
      description: |
        **Used by internal tru.ID applications only**.
        Log the current user out of an authenticated session with the OAuth2 provider.
      operationId: oauth2-sessions-logout
      security:
        - BasicAuth: []
      tags:
        - hide
      parameters:
        - name: id_token_hint
          description: The OAuth2 id token received when the client logged in
          schema:
            type: string
            example: token
          in: query
        - name: state
          description: "state that is played back to the client, when successfully redirected to the `post_logout_redirect_uri`"
          schema:
            type: string
            example: token
          in: query
        - name: post_logout_redirect_uri
          description: Where the browser client will be redirected to after a successful logout
          schema:
            type: string
            example: "https://example.com/logged_out"
          in: query
      responses:
        "302":
          description: Redirects to the `post_logout_redirect_uri`
          headers:
            Location:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Location
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached

  /console/v0.2/workspaces:
    get:
      summary: Get a collection of Workspaces
      description: "Get the list of workspaces"
      tags:
        - workspaces_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/schemas/WorkspaceCollection
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: get-console-v0.2-workspaces
      security:
        - WorkspaceBearerAuth: []
  "/console/v0.2/workspaces/{workspace_id}":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
    get:
      summary: Get a Workspace
      description: "Get a specific workspace"
      tags:
        - workspaces_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/schemas/WorkspaceFull
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: get-console-v0.2-workspace
      security:
        - WorkspaceBearerAuth: []

  "/console/v0.2/workspaces/{workspace_id}/members":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
    get:
      summary: Get a collection of Members
      description: "Get all members for the workspace identified by `workspace_id`"
      tags:
        - members_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/Member.v1.yaml#/components/schemas/MemberCollection
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: get-console-v0.2-workspace-members
      security:
        - WorkspaceBearerAuth: []
  "/console/v0.2/workspaces/{workspace_id}/members/{member_id}":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/memberId
    get:
      summary: Get a Member
      description: "Get a Member identified by `member_id`"
      tags:
        - members_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/Member.v1.yaml#/components/schemas/MemberFull
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: get-console-v0.2-workspace-member
      security:
        - WorkspaceBearerAuth: []

  "/console/v0.2/workspaces/{workspace_id}/members/{member_id}/credentials":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/memberId
    get:
      summary: Get a collection of Workspace  Credentials
      description: "Get the Workspace Credentials created by the member identified by `member_id`"
      tags:
        - members_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/schemas/WorkspaceCredentialCollection
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: get-console-v0.2-workspace-member-credentials
      security:
        - WorkspaceBearerAuth: []
    post:
      summary: Create a Workspace Credential
      description: "Create workspace credential associated with a specific member"
      tags:
        - members_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/schemas/WorkspaceCredential
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: post-console-v0.2-workspace-member-credential-create
      security:
        - WorkspaceBearerAuth: []

  "/console/v0.2/workspaces/{workspace_id}/members/{member_id}/credentials/{client_id}":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/memberId
      - $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/parameters/clientId
    get:
      summary: Get a Workspace Credential
      description: "Get the Workspace Credential identified by `client_id`"
      tags:
        - members_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/schemas/WorkspaceCredential
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: get-console-v0.2-workspace-member-credential
      security:
        - WorkspaceBearerAuth: []
    delete:
      summary: Delete a Workspace Credential
      description: "Delete the Workspace Credential identified by `client_id`"
      tags:
        - members_v0.2
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      operationId: delete-console-v0.2-workspace-member-credential
      security:
        - WorkspaceBearerAuth: []

  "/console/v0.2/workspaces/{workspace_id}/projects":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
    post:
      summary: Create a Project
      description: Create a Project
      operationId: post-console-v0.2-workspace-projects
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      requestBody:
        description: A JSON payload for the Project that is to be created.
        content:
          application/json:
            schema:
              $ref: ./models/console/ProjectResourceModels.v2.yaml#/components/schemas/CreateProjectPayload
            examples:
              basic:
                value:
                  name: My test project
      responses:
        "201":
          description: Created
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/ProjectResourceModels.v2.yaml#/components/schemas/ProjectCreated
              examples:
                basic:
                  value:
                    project_id: c69bc0e6-a429-11ea-bb37-0242ac130003
                    name: My test project
                    created_at: "2020-06-01T16:43:30+00:00"
                    updated_at: "2020-06-01T16:43:30+00:00"
                    _links:
                      self:
                        href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/projects/c69bc0e6-a429-11ea-bb37-0242ac130003
                      my_credentials:
                        href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/projects/c69bc0e6-a429-11ea-bb37-0242ac130003/credentials?search==member_id
                    _embedded:
                      credentials:
                        - client_id: 6779ef20e75817b79602
                          client_secret: 6779ef20e75
                          scopes:
                            - phone_check
                          created_at: "2020-06-01T16:43:30+00:00"
                          updated_at: "2020-06-01T16:43:30+00:00"
                          _links:
                            self:
                              href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/projects/c69bc0e6-a429-11ea-bb37-0242ac130003/credentials/6779ef20e75817b79602
                            member:
                              href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/members/c78ac34e-20b9-47dc-a070-c0abec1a3c61

        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
      callbacks:
        projectLevelPhoneCheckEndStatus:
          "{$request.body#/configuration.phone_check.callback_url}":
            post:
              summary: PhoneCheck has reached an end status
              parameters:
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/x-tru-security
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/x-tru-callback
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/digest
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/date
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/host
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: ./models/phone_check/PhoneCheckResourceModels.v0.1.yaml#/components/schemas/PhoneCheckCallbackPayload
              responses:
                $ref: ./models/common/Responses.v1.yaml#/components/responses/WebHookExpectedResponse
    get:
      summary: Get a collection of Projects
      description: Get a full list of Projects or filter by query parameter.
      operationId: get-console-v0.2-workspace-projects
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      parameters:
        - name: name
          description: The name of the project
          schema:
            type: string
            example: hello
          in: query
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageSize
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageNumber
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/search
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/sort
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/ProjectResourceModels.v2.yaml#/components/schemas/ProjectCollection
              examples:
                basic:
                  value:
                    page:
                      size: 10
                      number: 1
                      total_pages: 1
                      total_elements: 2
                    _embedded:
                      projects:
                        - _links:
                            self:
                              href: /projects/c69bc0e6-a429-11ea-bb37-0242ac130002
                            my_credentials:
                              href: /projects/c69bc0e6-a429-11ea-bb37-0242ac130002/credentials
                          project_id: c69bc0e6-a429-11ea-bb37-0242ac130002
                          name: My first project
                          created_at: "2020-06-01T16:43:30+00:00"
                          updated_at: "2020-06-01T16:43:30+00:00"
                          member_id: c78ac34e-20b9-47dc-a070-c0abec1a3c61
                        - _links:
                            self:
                              href: /projects/c69bc0e6-a429-11ea-bb37-0242ac130003
                            my_credentials:
                              href: /projects/c69bc0e6-a429-11ea-bb37-0242ac130002/credentials
                          project_id: c69bc0e6-a429-11ea-bb37-0242ac130003
                          name: My second project
                          created_at: "2020-06-01T16:43:30+00:00"
                          updated_at: "2020-06-01T16:43:30+00:00"
                          member_id: c78ac34e-20b9-47dc-a070-c0abec1a3c61
                    _links:
                      first:
                        href: /projects/page=1&size=10
                      last:
                        href: /projects/page=3&size=10
                      next:
                        href: /projects/page=3&size=10
                      prev:
                        href: /projects/page=1&size=10
                      self:
                        href: /projects/page=2&size=10
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached

  "/console/v0.2/workspaces/{workspace_id}/projects/{project_id}":
    parameters:
      - $ref: ./models/common/ProjectCommon.v1.yaml#/components/parameters/projectId
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
    get:
      summary: Get a Project
      description: Get a Project identified by `project_id`.
      operationId: get-console-v0.2-workspace-project
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/ProjectResourceModels.v2.yaml#/components/schemas/Project
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
    patch:
      summary: Update a Project
      description: Update the project identified by the `project_id`.
      operationId: patch-console-v0.2-workspace-project
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      requestBody:
        description: A JSON payload for the Project that is to be created.
        content:
          application/json-patch+json:
            schema:
              $ref: ./models/common/ProjectCommon.v1.yaml#/components/schemas/ProjectPatchPayload
            examples:
              change_mode:
                summary: Change the Project mode to `live`
                value:
                  - op: replace
                    path: /mode
                    value: live
              change_name:
                summary: Change the Project name
                value:
                  - op: replace
                    path: /name
                    value: my-new-name
              add_callback_url:
                summary: Add a `callback_url` to the Project configuration
                value:
                  - op: add
                    path: /configuration
                    value:
                      phone_check:
                        callback_url: "https://example.com/callback"
              replace_callback_url:
                summary: Replace a `callback_url` for a Project configuration
                value:
                  - op: replace
                    path: /configuration/phone_check/callback_url
                    value: "https://example.com/updated_callback"
              remove_callback_url:
                summary: Remove the `callback_url` from the Project configuration
                value:
                  - op: remove
                    path: /configuration/phone_check/callback_url
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/console/ProjectResourceModels.v2.yaml#/components/schemas/Project
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached

  "/console/v0.2/workspaces/{workspace_id}/projects/{project_id}/credentials/{client_id}":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
      - $ref: ./models/common/ProjectCommon.v1.yaml#/components/parameters/projectId
      - $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/parameters/clientId
    get:
      summary: Get Project Credential
      description: "Get the Project Credential identified by `client_id`"
      operationId: get-console-v0.2-workspace-project-credential
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/schemas/ProjectCredential
              examples:
                basic:
                  value:
                    client_id: 8cbd640e-2cbf-42d1-bd57-421169144300
                    scopes:
                      - phone_check
                    created_at: "2020-06-01T16:43:30+00:00"
                    updated_at: "2020-06-01T16:43:30+00:00"
                    _embedded:
                      created_by:
                        member_id: c78ac34e-20b9-47dc-a070-c0abec1a3c61
                        name: John Brown
                        _links:
                          self:
                            href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/members/c78ac34e-20b9-47dc-a070-c0abec1a3c61
                    _links:
                      self:
                        href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/projects/123cccb-20b9-47dc-a070-c0abec1a3c61/credentials/8cbd640e-2cbf-42d1-bd57-421169144300
                      member:
                        href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/members/c78ac34e-20b9-47dc-a070-c0abec1a3c61

          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
    delete:
      summary: Delete Project Credential
      description: "Delete the Project Credential identified by `client_id`"
      operationId: delete-console-v0.2-workspace-project-credential
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached

  "/console/v0.2/workspaces/{workspace_id}/projects/{project_id}/credentials":
    parameters:
      - $ref: ./models/console/WorkspaceResourceModels.v2.yaml#/components/parameters/workspaceId
      - $ref: ./models/common/ProjectCommon.v1.yaml#/components/parameters/projectId
    get:
      summary: Get a collection of Project Credentials
      description: "Get the collection of Project Credentials for the project identified by `project_id`"
      operationId: get-console-v0.2-workspace-project-credentials
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/schemas/ProjectCredentialCollection
              examples:
                basic:
                  value:
                    page:
                      size: 10
                      number: 1
                      total_pages: 1
                      total_elements: 2
                    _embedded:
                      credentials:
                        - client_id: 8cbd640e-2cbf-42d1-bd57-421169144300
                          scopes:
                            - phone_check
                          created_at: "2020-06-01T16:43:30+00:00"
                          updated_at: "2020-06-01T16:43:30+00:00"
                          _embedded:
                            created_by:
                              member_id: c78ac34e-20b9-47dc-a070-c0abec1a3c61
                              name: John Brown
                              _links:
                                self:
                                  href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/members/c78ac34e-20b9-47dc-a070-c0abec1a3c61
                          _links:
                            self:
                              href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/projects/c69bc0e6-a429-11ea-bb37-0242ac130002/credentials/8cbd640e-2cbf-42d1-bd57-421169144300
                            member:
                              href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/members/c78ac34e-20b9-47dc-a070-c0abec1a3c61
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached
    post:
      summary: Create Project Credential
      description: "Create Project Credential for the project identified by `project_id`"
      operationId: post-console-v0.2-workspace-project-credential
      security:
        - WorkspaceBearerAuth: []
      tags:
        - projects_v0.2
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/console/CredentialResourceModels.v1.yaml#/components/schemas/ProjectCredential
              examples:
                basic:
                  value:
                    client_id: 8cbd640e-2cbf-42d1-bd57-421169144300
                    scopes:
                      - phone_check
                    created_at: "2020-06-01T16:43:30+00:00"
                    updated_at: "2020-06-01T16:43:30+00:00"
                    _embedded:
                      created_by:
                        member_id: c78ac34e-20b9-47dc-a070-c0abec1a3c61
                        name: John Brown
                        _links:
                          self:
                            href: /console/v0.2/workspaces/8d2ad339-8f11-4858-9623-a20c42b79acf/members/c78ac34e-20b9-47dc-a070-c0abec1a3c61
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            X-RateLimit-Reset:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Reset
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/Forbidden
        "429":
          description: Rate Limit Reached
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/RateLimitReached

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    WorkspaceBearerAuth:
      description: |
        The tru.ID APIs expect the bearer token to be a [OAuth2 Access Token](https://tools.ietf.org/html/rfc6749#section-1.4). The access token should be within the `Authorization` HTTP header.
        e.g. `Authorization: Bearer {access_token}`.

        The token should be a Workspace-level access token. These are created using your Workspace `client_id` and `client_secret`. See [Create an Access Token](#operation/oauth2-token).
      type: http
      scheme: bearer
  schemas:
    OAuth2Scope:
      description: |
        The scope of the access request. A spaced delimited list of scopes representing the resources the Access Token provides access to.

        - `console`: `/console/{version}` resources. From version 0.2.
        - `phone_check`: `/phone_check` resources
        - `subscriber_check`: `/subscriber_check` resources
        - `sim_check`: `/sim_check` resources
        - `coverage`: `/coverage` resources
      type: string
      example: phone_check subscriber_check sim_check
  parameters:
    scope:
      name: scope
      description: |
        A spaced delimited list of scopes representing the resources the Access Token provides access to.
      in: query
      schema:
        $ref: "#/components/schemas/OAuth2Scope"
