openapi: 3.0.0
info:
  title: tru.ID APIs
  version: v0.1
  contact:
    name: tru.ID API Team
    email: feedback@tru.id
  description: |
    # Introduction

    The tru.ID API uses [OAuth2](#tag/oauth2) Access Tokens for authentication. Access Tokens are created using the [/token endpoint](#operation/oauth2-token) with a valid `client_id` and `client_secret`. `client_id` and `client_secret` credentials are obtained by [creating a Project](#operation/create-project).

    The [**tru.ID PhoneCheck Workflow** and API](#tag/phone_check) confirms the ownership of a mobile phone number by verifying the possession of an active SIM card with the same number. A mobile data session is created to a unique **PhoneCheck URL** for the purpose of this verification. **tru.ID** then resolves a **PhoneCheck Match** between the phone number that the mobile network operator identifies as the owner of the mobile data session and the phone number being verified.

    The [**tru.ID SIMCheck API**](#tag/sim_check) provides information on when a SIM card associated with a mobile phone number last changed

    The [**tru.ID SubscriberCheck Workflow** and API](#tag/subscriber_check) combines the functionality offerd by PhoneCheck and SIMCheck into a single API. It confirms the ownership of a mobile phone number and provides information on when the SIM card associated with the mobile phone number last changed..
servers:
  - url: "https://{data_residency}.api.tru.id"
    description: For accounts with data residency in the EU
    variables:
      data_residency:
        default: eu
        enum:
          - eu
tags:
  - name: oauth2_v1
    x-displayName: v1
    description: Relating to the OAuth2 Provider
  - name: phone_check_v0.1
    x-displayName: v0.1
    description: Relating to PhoneCheck
  - name: subscriber_check_v0.1
    x-displayName: v0.1
    description: Relating to SubscriberCheck

x-tagGroups:
  - name: oAuth2
    tags:
      - oauth2_v1
  - name: PhoneCheck
    tags:
      - phone_check_v0.1
  - name: SubscriberCheck
    tags:
      - subscriber_check_v0.1

paths:
  /oauth2/v1/auth:
    get:
      summary: Obtain an authorization grant (Restricted Usage)
      description: "Used within the OAuth2 flow. Used to request access to a resource from the resource owner. Only supported for tru.ID owned applications. See https://tools.ietf.org/html/rfc6749#section-3.1"
      operationId: oauth2-auth
      tags:
        - hide
      parameters:
        - name: response_type
          description: "Used as part of an Authorization Code Grant. Expected to have a value of `code`. See https://tools.ietf.org/html/rfc6749#section-4.1"
          in: query
          schema:
            type: string
            example: code
        - name: client_id
          description: The client identifier. Only issued for use with `/auth` to internal tru.ID applications.
          in: query
          schema:
            type: string
            example: 63f16604-2b4f-4e45-b32f-59290507fe93
        - name: state
          description: |
            An opaque value used by the client to maintain state between the request and callback. The authorization server includes this value when redirecting the user-agent back to the client.
            See: https://tools.ietf.org/html/rfc6749#section-4.1.1"
          in: query
          schema:
            type: string
        - $ref: "#/components/parameters/scope"
        - name: redirect_url
          description: "After completing the interaction with the resource owner, the authorization server directs the resource owner's user-agent back the location identified by `redirect_url`."
          in: query
          schema:
            type: string
            format: uri
      responses:
        "302":
          description: Redirects to the `redirect_url`.
          headers:
            Location:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Location
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
  /oauth2/v1/token:
    post:
      summary: Create an Access Token
      description: |
        Creates an Access Token. Access Tokens are credentails used to authenticate API interactions.
        With the tru.ID platform, the usage is to create an Access Token from a `client_id` and `client_secret`.

        To obtain a `client_id` and `client_secret` you must first [create a Project](#operation/create-project).
      operationId: oauth2-token
      security:
        - BasicAuth: []
      tags:
        - oauth2_v1
      requestBody:
        description: |
          The request body should match the [Client Credentails Grant](https://tools.ietf.org/html/rfc6749#section-4.4) flow.
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              description: |
                Create an Access Token authenticated using a `client_id` and `client_secret` as part of a [Client Credentails Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
                The resulting token is used to access any API endpoints.
              properties:
                grant_type:
                  description: |
                    The type of grant; in this case a [Client Credentails Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
                    Value must be set to `client_credentials`.
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                scope:
                  $ref: "#/components/schemas/OAuth2Scope"
      responses:
        "200":
          description: The Access Token was successfully created.
          content:
            application/json:
              schema:
                type: object
                description: |
                  The response to a [Client Credentails Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
                properties:
                  access_token:
                    description: The Access Token to be used when authenticating with API endpoints
                    type: string
                    example: 2YotnFZFEjr1zCsicMWpAA
                  token_type:
                    description: |
                      The type of token in `access_token`. The token type returned will always be `bearer`.
                      For more information see [The OAuth 2.0 Authorization Framework: Bearer Token Usage](https://tools.ietf.org/html/rfc6750)
                    type: string
                    enum:
                      - bearer
                    example: bearer
                  expires_in:
                    description: The time in seconds when the token will expire.
                    type: integer
                    example: 3600
                  scope:
                    $ref: "#/components/schemas/OAuth2Scope"
              examples:
                phone_check:
                  value:
                    access_token: 2YotnFZFEjr1zCsicMWpAA
                    token_type: bearer
                    expires_in: 3600
                    scope: phone_check coverage
  /oauth2/v1/revoke:
    post:
      summary: Revoke an token
      description: Revoke a token from the OAuth2 provider.
      operationId: oauth2-revoke
      security:
        - BasicAuth: []
      tags:
        - oauth2_v1
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              description: |
                The response to a [Client Credentails Grant](https://tools.ietf.org/html/rfc6749#section-4.4).
              properties:
                token:
                  description: The token to be revoked
                  type: string
                  example: 2YotnFZFEjr1zCsicMWpAA
                token_type_hint:
                  description: A hint to help the OAuth2 provider identify the type of token
                  type: string
                  enum:
                    - access_token
                    - refresh_token
                  example: access_token
      responses:
        "200":
          description: Response whether the Access Token was valid or invalid.
  /oauth2/v1/sessions/logout:
    get:
      summary: Logout of the current user session (Restricted Usage)
      description: |
        **Used by internal tru.ID applications only**.
        Log the current user out of an authenticated session with the OAuth2 provider.
      operationId: oauth2-sessions-logout
      security:
        - BasicAuth: []
      tags:
        - hide
      parameters:
        - name: id_token_hint
          description: The OAuth2 id token received when the client logged in
          schema:
            type: string
            example: token
          in: query
        - name: state
          description: "state that is played back to the client, when successfully redirected to the `post_logout_redirect_uri`"
          schema:
            type: string
            example: token
          in: query
        - name: post_logout_redirect_uri
          description: Where the browser client will be redirected to after a successful logout
          schema:
            type: string
            example: "https://example.com/logged_out"
          in: query
      responses:
        "302":
          description: Redirects to the `post_logout_redirect_uri`
          headers:
            Location:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Location
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining

  /phone_check/v0.1/checks:
    post:
      summary: Create a PhoneCheck workflow
      description: |
        Starts the PhoneCheck workflow.
      operationId: create-phone-check
      security:
        - ProjectBearerAuth: []
      tags:
        - phone_check_v0.1
      requestBody:
        description: JSON payload to create a PhoneCheck
        content:
          application/json:
            schema:
              $ref: ./models/phone_check/PhoneCheckResourceModels.v1.yaml#/components/schemas/PhoneCheckCreatePayload
      callbacks:
        phoneCheckEndStatus:
          "{$request.body#/callback_url}":
            post:
              summary: PhoneCheck has reached an end status
              parameters:
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/x-tru-security
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/x-tru-callback
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/digest
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/date
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/host
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: ./models/phone_check/PhoneCheckResourceModels.v1.yaml#/components/schemas/PhoneCheckCallbackPayload
              responses:
                $ref: ./models/common/Responses.v1.yaml#/components/responses/WebHookExpectedResponse
      responses:
        "201":
          description: PhoneCheck created
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                allOf:
                  - $ref: ./models/phone_check/PhoneCheckResourceModels.v1.yaml#/components/schemas/PhoneCheckCreateResponse
                 
                    
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                oneOf:
                  - $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/InvalidPhoneNumberFormat
                  - type: object
                    allOf:
                      - $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/ProblemDetailsBase
                      - type: object
                        description: The country for the supplied `phone_number` is not supported
    get:
      summary: Get a collection of PhoneChecks
      operationId: get-phone-checks
      description: Get a full list of PhoneChecks or filter by query parameter.
      security:
        - ProjectBearerAuth: []
      tags:
        - phone_check_v0.1
      parameters:
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageSize
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageNumber
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/search
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/sort
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/phone_check/PhoneCheckResourceModels.v1.yaml#/components/schemas/PhoneCheckCollection
  "/phone_check/v0.1/checks/{check_id}":
    parameters:
      - name: check_id
        description: The ID of the PhoneCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Get PhoneCheck
      description: "Get a PhoneCheck identified by `check_id`. NB: if the user never visits the `check_url`, after 60 seconds the Check will be deleted and 404 returned."
      operationId: get-phone-check
      security:
        - ProjectBearerAuth: []
      tags:
        - phone_check_v0.1
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/phone_check/PhoneCheckResourceModels.v1.yaml#/components/schemas/PhoneCheck
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/phone_check/v0.1/checks/{check_id}/redirect":
    parameters:
      - name: check_id
        description: The ID of the PhoneCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Perform the PhoneCheck
      description: Perform the PhoneCheck identified by `check_id`.
      operationId: get-phone-check-redirect
      tags:
        - phone_check_v0.1
      responses:
        "302":
          description: Redirects to the `check_url`.
          headers:
            Location:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Location
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
        "400":
          description: Mobile Network Operator Not Supported
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/MobileNetworkOperatorNotSupported
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "412":
          description: Not a mobile IP
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotMobileIp
  "/phone_check/v0.1/checks/{check_id}/traces":
    parameters:
      - name: check_id
        description: The ID of the PhoneCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Get a collection of PhoneCheck Traces
      description: Get Traces of the PhoneCheck identified by `check_id`
      operationId: get-phone-check-traces
      tags:
        - phone_check_v0.1
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/trace/TraceResourceModels.v1.yaml#/components/schemas/TraceCollection
              examples:
                basic:
                  value:
                    _embedded:
                      traces:
                        - _links:
                            self:
                              href: "https://eu.api.tru.id/phone_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/6f2a0e25fc0caa25"
                          trace_id: 6f2a0e25fc0caa25
                          logs:
                            - timestamp: "2021-02-05T13:58:48.751Z"
                              message: "Check create: phone number is reachable"
                            - timestamp: "2021-02-05T13:58:48.856Z"
                              message: "Check balance: authorized"
                              attributes:
                                amount: 1
                                currency: API
                            - timestamp: "2021-02-05T13:58:48.864Z"
                              message: "Check create: accepted"
                        - _links:
                            self:
                              href: "https://eu.api.tru.id/phone_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/7f1bc78ab197ee8b"
                          trace_id: 7f1bc78ab197ee8b
                          logs:
                            - timestamp: "2021-02-05T13:59:05.060Z"
                              message: "Check balance: confirmed"
                              attributes:
                                amount: 1
                                currency: API
                    _links:
                      self:
                        href: "https://eu.api.tru.id/phone_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/phone_check/v0.1/checks/{check_id}/traces/{trace_id}":
    parameters:
      - name: check_id
        description: The ID of the PhoneCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
      - name: trace_id
        description: The ID of the Trace
        schema:
          type: string
        in: path
        required: true
    get:
      summary: Get PhoneCheck Trace
      description: Get the Trace identified by `trace_id` of the PhoneCheck identified by `check_id`
      operationId: get-phone-check-trace
      tags:
        - phone_check_v0.1
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/trace/TraceResourceModels.v1.yaml#/components/schemas/TraceResource
              examples:
                basic:
                  value:
                    trace_id: 6f2a0e25fc0caa25
                    logs:
                      - timestamp: "2021-02-05T13:58:48.751Z"
                        message: "Check create: request accepted"
                      - timestamp: "2021-02-05T13:58:48.824Z"
                        message: "Check create: phone number is routable"
                      - timestamp: "2021-02-05T13:58:48.856Z"
                        message: "Check balance: authorized"
                        attributes:
                          amount: 1
                          currency_code: API
                      - timestamp: "2021-02-05T13:58:48.864Z"
                        message: "Check create: successful "
                    _links:
                      self:
                        href: "https://eu.api.tru.id/phone_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/6f2a0e25fc0caa25"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  /subscriber_check/v0.1/checks:
    post:
      summary: Create an SubscriberCheck workflow
      description: |
        Starts the SubscriberCheck workflow.
      operationId: create-subscriber-check
      security:
        - ProjectBearerAuth: []
      tags:
        - subscriber_check_v0.1
      requestBody:
        description: JSON payload to create an SubscriberCheck
        content:
          application/json:
            schema:
              $ref: ./models/subscriber_check/SubscriberCheckResourceModels.v1.yaml#/components/schemas/SubscriberCheckCreatePayload
      callbacks:
        phoneCheckEndStatus:
          "{$request.body#/callback_url}":
            post:
              summary: SubscriberCheck has reached an end status
              parameters:
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/x-tru-security
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/x-tru-callback
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/digest
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/date
                - $ref: ./models/common/Headers.v1.yaml#/components/headers/host
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: ./models/subscriber_check/SubscriberCheckResourceModels.v1.yaml#/components/schemas/SubscriberCheckCallbackPayload
              responses:
                $ref: ./models/common/Responses.v1.yaml#/components/responses/WebHookExpectedResponse
      responses:
        "201":
          description: SubscriberCheck created
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                allOf:
                  - $ref: ./models/subscriber_check/SubscriberCheckResourceModels.v1.yaml#/components/schemas/SubscriberCheckCreateResponse
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                oneOf:
                  - $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/InvalidPhoneNumberFormat
                  - type: object
                    allOf:
                      - $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/ProblemDetailsBase
                      - type: object
                        description: The country for the supplied `phone_number` is not supported
    get:
      summary: Get a collection of SubscriberChecks
      operationId: get-subscriber-checks
      description: Get a full list of SubscriberChecks or filter by query parameter.
      security:
        - ProjectBearerAuth: []
      tags:
        - subscriber_check_v0.1
      parameters:
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageSize
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/pageNumber
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/search
        - $ref: ./models/common/PageBasedPagination.v1.yaml#/components/parameters/sort
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/subscriber_check/SubscriberCheckResourceModels.v1.yaml#/components/schemas/SubscriberCheckCollection
  "/subscriber_check/v0.1/checks/{check_id}":
    parameters:
      - name: check_id
        description: The ID of the SubscriberCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Get SubscriberCheck
      description: Get a SubscriberCheck identified by `check_id`.
      operationId: get-subscriber-check
      security:
        - ProjectBearerAuth: []
      tags:
        - subscriber_check_v0.1
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ./models/subscriber_check/SubscriberCheckResourceModels.v1.yaml#/components/schemas/SubscriberCheck
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/subscriber_check/v0.1/checks/{check_id}/redirect":
    parameters:
      - name: check_id
        description: The ID of the SubscriberCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Perform the SubscriberCheck
      description: Perform the SubscriberCheck identified by `check_id`.
      operationId: get-subscriber-check-redirect
      tags:
        - subscriber_check_v0.1
      responses:
        "302":
          description: Redirects to the `check_url`.
          headers:
            Location:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Location
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
        "400":
          description: Mobile Network Operator Not Supported
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/MobileNetworkOperatorNotSupported
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
        "412":
          description: Not a mobile IP
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotMobileIp
  "/subscriber_check/v0.1/checks/{check_id}/traces":
    parameters:
      - name: check_id
        description: The ID of the SubscriberCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
    get:
      summary: Get a collection of SubscriberCheck Traces
      description: Get Traces of the SubscriberCheck identified by `check_id`
      operationId: get-subscriber-check-traces
      tags:
        - subscriber_check_v0.1
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/trace/TraceResourceModels.v1.yaml#/components/schemas/TraceCollection
              examples:
                basic:
                  value:
                    _embedded:
                      traces:
                        - _links:
                            self:
                              href: "https://eu.api.tru.id/subscriber_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/6f2a0e25fc0caa25"
                          trace_id: 6f2a0e25fc0caa25
                          logs:
                            - timestamp: "2021-02-05T13:58:48.751Z"
                              message: "Check create: phone number is reachable"
                            - timestamp: "2021-02-05T13:58:48.856Z"
                              message: "Check balance: authorized"
                              attributes:
                                amount: 1
                                currency: API
                            - timestamp: "2021-02-05T13:58:48.864Z"
                              message: "Check create: accepted"
                        - _links:
                            self:
                              href: "https://eu.api.tru.id/subscriber_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/7f1bc78ab197ee8b"
                          trace_id: 7f1bc78ab197ee8b
                          logs:
                            - timestamp: "2021-02-05T13:59:05.060Z"
                              message: "Check balance: confirmed"
                              attributes:
                                amount: 1
                                currency: API
                    _links:
                      self:
                        href: "https://eu.api.tru.id/subscriber_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound
  "/subscriber_check/v0.1/checks/{check_id}/traces/{trace_id}":
    parameters:
      - name: check_id
        description: The ID of the SubscriberCheck
        schema:
          $ref: ./models/common/DataTypes.v1.yaml#/components/schemas/UUID
        in: path
        required: true
      - name: trace_id
        description: The ID of the of the Trace
        schema:
          type: string
        in: path
        required: true
    get:
      summary: Get SubscriberCheck Trace
      description: Get the Trace identified by `trace_id`  of the SubscriberCheck identified by `check_id`
      operationId: get-subscriber-check-trace
      tags:
        - subscriber_check_v0.1
      responses:
        "200":
          description: OK
          headers:
            X-RateLimit-Limit:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Limit
            X-RateLimit-Remaining:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/X-RateLimit-Remaining
            Access-Control-Allow-Origin:
              $ref: ./models/common/Headers.v1.yaml#/components/headers/Access-Control-Allow-Origin-All
          content:
            application/hal+json:
              schema:
                $ref: ./models/trace/TraceResourceModels.v1.yaml#/components/schemas/TraceResource
              examples:
                basic:
                  value:
                    trace_id: 6f2a0e25fc0caa25
                    logs:
                      - timestamp: "2021-02-05T13:58:48.751Z"
                        message: "Check create: phone number is reachable"
                      - timestamp: "2021-02-05T13:58:48.856Z"
                        message: "Check balance: authorized"
                        attributes:
                          amount: 1
                          currency: API
                      - timestamp: "2021-02-05T13:58:48.864Z"
                        message: "Check create: accepted"
                        _links:
                          self:
                            href: "https://eu.api.tru.id/subscriber_check/v0.1/checks/857b1bab-c2e8-41ec-9f76-9695ec78b91b/traces/6f2a0e25fc0caa25"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: ./models/common/HTTPProblemDetailTypes.v1.yaml#/components/responses/NotFound

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    WorkspaceBearerAuth:
      description: |
        The tru.ID APIs expect the bearer token to be a [OAuth2 Access Token](https://tools.ietf.org/html/rfc6749#section-1.4). The access token should be within the `Authorization` HTTP header.
        e.g. `Authorization: Bearer {access_token}`

        The token should be a Workspace-level access token. These are created using your Workspace `client_id` and `client_secret`.
      type: http
      scheme: bearer
    ProjectBearerAuth:
      description: |
        The tru.ID APIs expect the bearer token to be a [OAuth2 Access Token](https://tools.ietf.org/html/rfc6749#section-1.4). The access token should be within the `Authorization` HTTP header.
        e.g. `Authorization: Bearer {access_token}`. See [Create an Access Token](#operation/oauth2-token).

        The token should be associated with **tru.ID** Project. These are created using a Project `client_id` and `client_secret`. See [Create an Access Token](#operation/oauth2-token).
      type: http
      scheme: bearer
    UserBearerAuth:
      type: http
      scheme: bearer
  schemas:
    OAuth2Scope:
      description: |
        The scope of the access request. A spaced delimited list of scopes representing the resources the Access Token provides access to.

        - `console`: `/console/{version}` resources. From version 0.2.
        - `projects`: `/console/v0.1/projects` resources
        - `workspaces`: `/console/v0.1/workspaces` resources
        - `phone_check`: `/phone_check` resources
        - `subscriber_check`: `/subscriber_check` resources
        - `sim_check`: `/sim_check` resources
        - `coverage`: `/coverage` resources
        - `usage`: `/console/v0.1/workspaces/default/usage` resources
      type: string
      example: phone_check subscriber_check sim_check
  parameters:
    scope:
      name: scope
      description: |
        A spaced delimited list of scopes representing the resources the Access Token provides access to.
      in: query
      schema:
        $ref: "#/components/schemas/OAuth2Scope"
